Modified: 1	noremacDoc/git-noremacDoc 2	^ : usage() 3	^ : version() 4	^ : main()
Reasons:
1	Updated the descriptions on usage and main, they were the same as
	version. Added dates to the @src attributes.
2	I made it look nicer, seperated out the two commands.
^	Incremented the version.
3	Added a short description of what the extension is supposed to do.
4	Added @error 1-3

diff --git a/noremacDoc/git-noremacDoc b/noremacDoc/git-noremacDoc
--- a/noremacDoc/git-noremacDoc
+++ b/noremacDoc/git-noremacDoc
@@ -7,86 +7,132 @@
 #
 # @modified NoremacSkich | 2014/07/08
 #
-# @src http://goo.gl/r1TI4o
+# @src http://goo.gl/r1TI4o | 2014/07/08
 #
 version() {
-	echo "noremacDoc v0.1.1"
-	echo
+	echo "noremacDoc v0.1.2"
 }
 
 ##@fun usage()
-#	^	Displays the version of this file
+#	^	This displays how to use noremcDoc
 #
 # @auth Adam Brett | 2013/07/12
 #
 # @modified NoremacSkich | 2014/07/08
 #
-# @src http://goo.gl/r1TI4o
+# @src http://goo.gl/r1TI4o | 2014/07/08
 #
 usage() {
-	echo "usage: git noremacDoc <subcommand>"
+	echo "noremacDoc is used to automatically create the commit file according to"
+	echo "the standards stated in CommitColors.html"
+	echo
+	echo "usage:"
+	echo "    git noremacDoc <subcommand>"
 	echo
 	echo "Available subcommands are:"
-	echo "hello <name>  Print out Hello World or Hello <name> (if provided)"
+	echo "    hello         Prints out \"Hello World\""
+	echo "    hello <name>  Prints out \"Hello <name>\""
 }
 
 ##@fun main()
-#	^	Displays the version of this file
+#	^	This is the primary function. Acts as a gateway to the 
+#		functionality of this extension.
 #
 # @auth Adam Brett | 2013/07/12
 #
 # @modified NoremacSkich | 2014/07/08
 #
-# @src http://goo.gl/r1TI4o
+# @error 1 | exit code
+#	C	You didn't specify a parameter or a subcommand
+#	F	Enter a valid parameter or subcommand
+#
+# @error 2 | exit code
+#	C	You didn't specify a valid subcommand
+#	F	Enter a valid subcommand
+#
+# @error 3 | exit code
+#	C	Unable to load extension using source command.
+#	F	No know fix at this time.
+#
+# @src http://goo.gl/r1TI4o | 2014/07/08
 #
 main() {
-	#if the number of options is less than 1
+	# if the number of options is less than 1
+	# Check to see if they specified a parameter or a subcommand
 	if [ "$#" -lt 1 ]; then
-		#Display the usage dialogue, then exit
-		#with fail status of 1
-		usage; exit 1
+		# if there isn't, then display how to use this function
+		usage
+		# Exit the function with error code of 1, to indicate that a 
+		# parameter or subcommand wasn't used
+		exit 1
 	fi
 	
-	#Create var to store first parameter
+	# Store the first subcommand in the subcommand variable
 	local subcommand="$1"
 	
-	#move the rest of the arguments up by one
+	# Shift will move the "pointer" from the first parameter to the
+	# second parameter.  This will allow passing of arguments to 
+	# either a parameter or subcommand.
 	shift
 	
-	#See if they inputed a valid subcommand, then exit successfully
-	#this is how switch is done in bash
+	# See if they inputed a valid parameter, then exit successfully
+	# Have case for invalid subcommand?
 	case "$subcommand" in
 		"-h"|"--help")
-		usage; exit 0
+			#Display how to use noremacDoc, and what it is used for
+			usage
+			#Gracefully exit the function
+			exit 0
 		;; #break
 		"-v"|"--version")
-		version; exit 0
+			#Display the version number of noremacDoc
+			version
+			#Gracefully exit the function
+			exit 0
 		;; #break
 	esac #end case
 	
-	#new variable, stores the working directory
-	#sed replaces \ with / (for windows users using cygwin)
+	# Get the current location of this file, and store it in WORKINGDIR.
+	# We need to be mindful of cygwin users, so we need to convert the 
+	# windows based file path to a linux file path. (eg replace \ with /)
 	local WORKINGDIR=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
 	
-	#see if subcommand exists, if not, exit with error 1
-	#while displaying usage
+	# With the parameters out of the way, lets see if they have specified a
+	# a subcommand.  We do this by checking if the script file for the 
+	# subcommand exists.
 	if [ ! -e "$WORKINGDIR/git-noremacDoc-$subcommand" ]; then
-		usage; exit 1
+		# If the script file doesn't exist then we need to inform them
+		# that it isn't a valid subcommand.
+		echo "$subcommand isn't a valid subcommand."
+
+		# Display the usage dialogue
+		usage
+
+		# Exit with an error of 2, to indicate incorrect subcommand.
+		exit 1
 	fi
 	
-	#The sub command works, now load it into the shell
+	# Now that we know that the subcommand is valid, we should load that
+	# script into the shell
 	source "$WORKINGDIR/git-noremacDoc-$subcommand"
 	
-	#test to make sure sub command exists, 
-	#if not, print usage and exit with error 1
+	# Test to see if the subcommand was loaded
 	if [ ! "type cmd_$subcommand" ]; then
-		usage; exit 1
+		# State it wasn't loaded
+		echo "Found $subcommand but could not load it into the current"
+		echo "shell successfully."
+
+		# exit extension with error of 3, to indicate the inability to
+		# load an extension.
+		exit 3
 	fi
 	
-	#Now run the sub command. Needs to be seperate from main function
+	# Now that the subcommand was loaded successfully, we need to 
+	# execute the command with the provided parameters.  This is where
+	# the shift from ealier comes in handy.  It will make sure that
+	# the subcommand will only get the arguments for it.
 	cmd_$subcommand "$@"
 }
-
-#now call the main function
+# With all that done, we need to call the main function.
 main "$@"
 
